-- Phase 5a: Authentication Setup
--
-- No SQL needs to be executed in this file.
-- Supabase Auth is managed entirely through the Dashboard.
--
-- ── Create a test user ────────────────────────────────────────────────────────
--
-- 1. Open your Supabase project Dashboard.
-- 2. Go to: Authentication → Users → "Invite user"
-- 3. Enter the email: admin@myerp.com
-- 4. Supabase will send an invite email with a link to set a password.
--    If email delivery is not configured, go to Authentication → Users,
--    find the user, and use "Send password reset" to set a password.
--
-- Alternatively, use "Add user" → "Create new user" to set a password immediately
-- (no email required in development):
--   Email: admin@myerp.com
--   Password: <choose a strong password — never hardcode it in source>
--
-- ── Notes ─────────────────────────────────────────────────────────────────────
--
-- This is an invite-only ERP — there is no public sign-up form.
-- Add new users only through the Supabase Dashboard.
